name: ascii-table
version: 0.3.0.0
synopsis: ASCII table
description: ASCII table
category: Data
github: Sentenai/ascii-table
license: BSD3
author: Sentenai
maintainer: mitchellwrosen@gmail.com
copyright: 2016 Sentenai, Inc.

ghc-options: -Wall

dependencies:
  - aeson
  - base                 >= 4.6 && < 5
  - containers
  - dlist
  - hashable
  - text
  - unordered-containers
  - vector
  - wl-pprint-extras     >= 1.3 && < 3.6

library:
  source-dirs: src
